var LEVEL_1_DATA = '<?xml version="1.0" encoding="UTF-8"?><level><tilemap scenename="gamescreen" tilewidth="64" tileheight="64">' +
'<tile type="block" x="1" y="0"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="2" y="0"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="3" y="0"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="4" y="0"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="5" y="0"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="6" y="0"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="7" y="0"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="8" y="0"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="9" y="0"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="10" y="0"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="1" y="7"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="2" y="7"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="3" y="7"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="4" y="7"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="5" y="7"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="6" y="7"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="7" y="7"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="8" y="7"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="9" y="7"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="10" y="7"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="0" y="0"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="0" y="1"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="0" y="2"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="0" y="3"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="0" y="4"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="0" y="5"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="0" y="6"><VectorList><VectorItem type="rectangle" fillstyle="#007700" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="0" y="7"><VectorList><VectorItem type="rectangle" fillstyle="#0000FF" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="11" y="0"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="11" y="1"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="11" y="2"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="11" y="3"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="11" y="4"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="11" y="5"><VectorList><VectorItem type="rectangle" fillstyle="#FF0000" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="11" y="6"><VectorList><VectorItem type="rectangle" fillstyle="#007700" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="11" y="7"><VectorList><VectorItem type="rectangle" fillstyle="#0000FF" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="1" y="6"><VectorList><VectorItem type="rectangle" fillstyle="#0000FF" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="2" y="6"><VectorList><VectorItem type="rectangle" fillstyle="#0000FF" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="1" y="5"><VectorList><VectorItem type="rectangle" fillstyle="#0000FF" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="8" y="3"><VectorList><VectorItem type="rectangle" fillstyle="#0000FF" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="9" y="3"><VectorList><VectorItem type="rectangle" fillstyle="#0000FF" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="10" y="3"><VectorList><VectorItem type="rectangle" fillstyle="#0000FF" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="9" y="4"><VectorList><VectorItem type="rectangle" fillstyle="#0000FF" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="10" y="4"><VectorList><VectorItem type="rectangle" fillstyle="#0000FF" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="4" y="3"><VectorList><VectorItem type="rectangle" fillstyle="#0000FF" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'<tile type="block" x="7" y="3"><VectorList><VectorItem type="rectangle" fillstyle="#0000FF" left="0" top="0" right="64" bottom="64"/></VectorList></tile>' +
'</tilemap>' +
'</level>';